### ISSUE TITLE
Fix viewtype definition

### ISSUE THREAD

**Issue by evertiro** [smitchell6879/plugin.specialfeatures#4]
Copied from forum post: https://forum.kodi.tv/showthread.php?tid=327042&pid=2711062#pid2711062

When launching special features from the video info dialog of a tvshow, the Container.Content is set to tvshows rather than videos. It needs to be set to videos for the correct viewtypes to be available.

**Comment by evertiro** [comment]
I actually haven't been able to replicate this issue...

**Comment by smitchell6879** [comment]
I have to a degree... But i made a few more changes to the views.. The containers will remain the way they are as for now it should go to videos... if it is a video file mp4,mkv,etc then kodi will extract a thumbnail however if it is a disc then it will keep the orginail poster. I will leave this issue open for now but unless something really changes i am happy with the way it works and dont plan on any changes here.

**Comment by evertiro** [comment]
It works fine for me. Everything tracks as video in all of my tests. I'm ok with this being closed unless it pops up again.

**Comment by smitchell6879** [comment]
Okay well i am going to close it for now we can always reopen it or start a new issue if it arises
