### ISSUE TITLE
Properly set window properties with plugin name

### ISSUE THREAD

**Issue by evertiro** [smitchell6879/plugin.specialfeatures#5]
Copied from forum post: https://forum.kodi.tv/showthread.php?tid=327042&pid=2711062#pid2711062

For official repo, you will need to change your window properties to be prefixed with the plugin name (see SkinHelper properties for e.g.)
e.g. something like Window(Home).Property(SpecialFeatures.HasContent) would be ideal

**Comment by smitchell6879** [comment]
SpecialFeatures.Content may be ideal but technically I am already doing this with sf_. If you think we should follow add the full name then we will have to redo all of your info dialogs as well. Let make a decision if we will stay with sf_ or if I need to bump and break everything you just added today.

**Comment by evertiro** [comment]
I can rework all my changes fairly quickly. They're pretty straightforward. If Kodi has a required standard, I see no reason not to follow it.

**Comment by smitchell6879** [comment]
Okay so I updated all the properties in all the files.
For the skins you can now use SpecialFeatures.Visible in place of sf_info. I think that was the only one being used by the skin-side. I also updated the others that are used internally.

From here on out I will prefix all properties with SpecialFeatures.
